services:
  minio:
    # https://hub.docker.com/r/minio/minio/tags
    image: minio/minio:RELEASE.2024-07-29T22-14-52Z
    container_name: sio-serv-minio-dev
    environment:
      - MINIO_ROOT_USER=sio-serv-admin-user
      - MINIO_ROOT_PASSWORD=sio-serv-admin-password
      - MINIO_IDENTITY_OPENID_CONFIG_URL=http://keycloak:8080/realms/dfast-dev/.well-known/openid-configuration
      - MINIO_IDENTITY_OPENID_CLIENT_ID=minio
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET=update-me
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME="Sigh In with Keycloak"
    volumes:
      - ${PWD}/minio-data:/data
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    restart: on-failure
    command: [ "server", "/data", "--console-address", ":9001" ]
    networks:
      - sio-serv-network

networks:
  sio-serv-network:
    name: sio-serv-network
    extenal: true
