services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sio-serv-app
    container_name: sio-serv-app
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
    environment:
      - SIO_SERV_KEYCLOAK_REALM_URL=http://localhost:8080/realms/sio-serv
      - SIO_SERV_KEYCLOAK_CLIENT_ID=sio-serv-app
      - SIO_SERV_MINIO_ENDPOINT=http://localhost:9000
      - SIO_SERV_SAPPORO_ENDPOINT=http://localhost:1122
      - SIO_SERV_WF_PARAMS_SCHEMA_FILE=/app/tests/wf-params-schema.json
      - SIO_SERV_UI_TABLE_FILE=/app/tests/ui-table.csv
      - SIO_SERV_RUN_REQUEST_FILE=/app/tests/run-request.json
      # - SIO_SERV_BASE_PATH=/something-wf/
    ports:
      - 127.0.0.1:3000:3000
    restart: on-failure
    working_dir: /app
    command: [ "sleep", "infinity" ]
    networks:
      - sio-serv-network
    init: true

  sapporo:
    image: ghcr.io/sapporo-wes/sapporo-service:2.0.5
    container_name: sio-serv-sapporo
    volumes:
      - ${PWD}/sapporo_config:/app/sapporo_config
      - ${PWD}/sapporo_run:${PWD}/sapporo_run
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      - SAPPORO_DEBUG=True
      - SAPPORO_RUN_DIR=${PWD}/sapporo_run
      - SAPPORO_SERVICE_INFO=/app/sapporo_config/service-info.json
      - SAPPORO_RUN_SH=/app/sapporo_config/run.sh
      - SAPPORO_AUTH_CONFIG=/app/sapporo_config/auth_config.json
    restart: on-failure
    working_dir: /app
    command: [ "sapporo" ]
    network_mode: host
    init: true

  keycloak:
    # https://hub.docker.com/r/keycloak/keycloak/tags
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: sio-serv-keycloak
    environment:
      - KEYCLOAK_ADMIN=sio-serv-admin-user
      - KEYCLOAK_ADMIN_PASSWORD=sio-serv-admin-password
    volumes:
      - ${PWD}/keycloak-data:/opt/keycloak/data
    ports:
      - 127.0.0.1:8080:8080
    restart: on-failure
    command: [ "start-dev" ]
    networks:
      - sio-serv-network

  minio:
    # https://hub.docker.com/r/minio/minio/tags
    image: minio/minio:RELEASE.2024-07-29T22-14-52Z
    container_name: sio-serv-minio
    environment:
      - MINIO_ROOT_USER=sio-serv-admin-user
      - MINIO_ROOT_PASSWORD=sio-serv-admin-password
      - MINIO_IDENTITY_OPENID_CONFIG_URL=http://localhost:8080/realms/sio-serv/.well-known/openid-configuration
      - MINIO_IDENTITY_OPENID_CLIENT_ID=sio-serv-minio
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET=SNCm0TrmLMCnJGudSpOsa72wSShHmwsu # This is a dummy secret (Please replace it with your own secret)
      - MINIO_IDENTITY_OPENID_CLAIM_NAME=policy
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME=Sigh In with Keycloak
    volumes:
      - ${PWD}/minio-data:/data
    restart: on-failure
    command: [ "server", "/data", "--console-address", ":9001" ]
    network_mode: host

volumes:
  node_modules: {}

networks:
  sio-serv-network:
    name: sio-serv-network
    external: true
