services:
  minio:
    # https://hub.docker.com/r/minio/minio/tags
    image: minio/minio:RELEASE.2024-07-29T22-14-52Z
    container_name: sio-serv-minio-dev
    environment:
      - MINIO_ROOT_USER=sio-serv-admin-user
      - MINIO_ROOT_PASSWORD=sio-serv-admin-password
      - MINIO_IDENTITY_OPENID_CONFIG_URL=http://localhost:8080/realms/sio-serv/.well-known/openid-configuration
      - MINIO_IDENTITY_OPENID_CLIENT_ID=sio-serv-minio
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET=PASTE_YOUR_CLIENT_SECRET_HERE
      - MINIO_IDENTITY_OPENID_CLAIM_NAME=policy
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME=Sigh In with Keycloak
    volumes:
      - ${PWD}/minio-data:/data
    restart: on-failure
    command: [ "server", "/data", "--console-address", ":9001" ]
    network_mode: host
