services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: sio-serv-dev
    container_name: sio-serv-dev
    environment:
      - SIO_SERV_KEYCLOAK_REALM_URL=http://localhost:8080/realms/sio-serv
      - SIO_SERV_KEYCLOAK_CLIENT_ID=sio-serv-spa
      - SIO_SERV_MINIO_ENDPOINT=http://localhost:9000
      - SIO_SERV_SAPPORO_ENDPOINT=http://localhost:1122
      - SIO_SERV_UI_TABLE_FILE=/app/tests/ui_table.tsv
      - SIO_SERV_WF_PARAMS_SCHEMA_FILE=/app/tests/wf_params_schema.json
      - SIO_SERV_RUN_REQUEST_FILE=/app/tests/run_request.json
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
    ports:
      - 127.0.0.1:3000:3000
    restart: on-failure
    working_dir: /app
    command: [ "sleep", "infinity" ]
    networks:
      - sio-serv-network

volumes:
  node_modules: {}

networks:
  sio-serv-network:
    name: sio-serv-network
    external: true
