/// <reference types="vite/client" />
declare const __APP_VERSION__: string
declare const KEYCLOAK_REALM_URL: string
declare const KEYCLOAK_CLIENT_ID: string
declare const MINIO_ENDPOINT: string
declare const SAPPORO_ENDPOINT: string
declare const UI_TABLE_FILE_CONTENT: string
declare const WF_PARAMS_SCHEMA_FILE_CONTENT: string
declare const RUN_REQUEST_FILE_CONTENT: string
