name: release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  deploy_ghcr:
    if: github.repository == 'sapporo-wes/sio-serv'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/sio-serv:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/sio-serv:latest

  create_release:
    if: github.repository == 'sapporo-wes/sio-serv'
    runs-on: ubuntu-22.04
    steps:
      - name: Create GitHub Release
        run: gh release create ${{ github.ref_name }} --title "${{ github.ref_name }}" --repo ${{ github.repository }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
